<?php
require_once("Conexion_BDD_MVC_Cap78.php");
$base=Conexion_BDD_MVC_Cap78::Conexion();
$tamano_paginas=3;
	if(isset($_GET["pagina"])){
		if($_GET["pagina"]==1){
		header("location:index_Cap78.php");
		}else{
		$pagina=$_GET["pagina"];
		}
	}else{
	$pagina=1;
	}	
	$inicio=($pagina-1)*$tamano_paginas;
	$sql_total="SELECT*FROM datos_usuarios";
	$resultado=$base->prepare($sql_total);
	$resultado->execute(array());
	$num_filas=$resultado->rowCount();
	$total_paginas=ceil($num_filas/$tamano_paginas);
?>